# Generated by Django 4.0.6 on 2022-08-26 05:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosticcenter', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=45)),
                ('Email', models.EmailField(max_length=45)),
                ('Feedbacktext', models.TextField()),
                ('Rating', models.IntegerField(default=1)),
                ('Date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
