# Generated by Django 4.0.6 on 2022-08-26 05:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosticcenter', '0005_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=45)),
                ('Test_name', models.CharField(max_length=100)),
                ('Booking_Type', models.CharField(max_length=20)),
                ('Date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
